# Generated by Django 2.2.16 on 2023-02-17 09:27

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20230217_1214'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='%(app_label)s_%(class)s_prevent_self_follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='self_follow'),
        ),
    ]
